export const FLAG_TYPES = {
  green: {
    label: "Green Flag",
    color: "#2e7d32",
    lightColor: "#4caf50",
    bg: "#0d2e10",
    icon: "checkmark-circle",
    description: "Beneficial or clean ingredients",
    simplyPut: "These ingredients are wholesome and generally good for you.",
    examples: ["whole oats", "olive oil", "turmeric", "almonds", "lentils", "spinach"],
  },
  neutral: {
    label: "White Flag",
    color: "#9ca3af",
    lightColor: "#d1d5db",
    bg: "#1f2937",
    icon: "ellipse-outline",
    description: "Neutral, okay in moderation",
    simplyPut: "Not harmful, but not particularly nutritious either.",
    examples: ["salt", "wheat flour", "citric acid", "yeast", "vinegar", "starch"],
  },
  red: {
    label: "Red Flag",
    color: "#c62828",
    lightColor: "#ef5350",
    bg: "#2e0d0d",
    icon: "flag",
    description: "Harmful or suspect, avoid where possible",
    simplyPut: "Linked to health concerns — try to limit or avoid.",
    examples: ["high fructose corn syrup", "trans fat", "MSG", "sodium nitrite", "BHA", "aspartame"],
  },
  allergen: {
    label: "Allergen Match",
    color: "#e94560",
    lightColor: "#ff6b85",
    bg: "#2e0a1a",
    icon: "warning",
    description: "Matches YOUR allergen list — dangerous",
    simplyPut: "This ingredient is on your personal allergen list.",
    examples: ["milk", "eggs", "peanuts", "soy", "wheat", "shellfish"],
  },
  unknown: {
    label: "Unknown",
    color: "#6b7280",
    lightColor: "#9ca3af",
    bg: "#111827",
    icon: "help-circle",
    description: "Not enough info to classify",
    simplyPut: "We don’t have enough data on this ingredient yet.",
    examples: ["proprietary blend", "natural flavour", "spices", "extract"],
  },
};